# Generated by Django 3.2 on 2023-07-22 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeuristicMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuristic_matching_edges', models.JSONField(blank=True, null=True)),
                ('execution_time', models.FloatField()),
                ('heuristic_matching', models.IntegerField()),
                ('heuristic_algorithm', models.CharField(choices=[('STATIC_MIN_DEGREE', 'Static Min Degree'), ('DYNAMIC_MIN_DEGREE', 'Dynamic Min Degree'), ('LIMIT_MIN_DEGREE', 'Limit Min Degree'), ('SIMPLE_GREEDY', 'Simple Greedy'), ('MONTE_CARLO', 'Monte Carlo'), ('RANDOMIZED_ROUNDING', 'Randomized Rounding'), ('MODIFIED_GREEDY', 'Modified Greedy')], db_index=True, max_length=50)),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_matching_edges', models.JSONField(blank=True, null=True)),
                ('execution_time', models.FloatField()),
                ('max_matching', models.IntegerField()),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_density', models.FloatField()),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('heuristic_matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.heuristicmatching')),
                ('max_matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.maxmatching')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
            options={
                'unique_together': {('user', 'worker', 'task')},
            },
        ),
        migrations.CreateModel(
            name='BipartiteGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('edges', models.ManyToManyField(blank=True, to='management.Edge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
