# Generated by Django 3.2 on 2023-10-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_matching_edges', models.JSONField(blank=True, null=True)),
                ('execution_time', models.FloatField()),
                ('max_matching', models.IntegerField()),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeuristicMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuristic_matching_edges', models.JSONField(blank=True, null=True)),
                ('execution_time', models.FloatField()),
                ('heuristic_matching', models.IntegerField()),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_density', models.FloatField()),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('heuristic_matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.heuristicmatching')),
                ('max_matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.maxmatching')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
