# Generated by Django 3.2 on 2023-08-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heuristicmatching',
            name='heuristic_algorithm',
        ),
    ]
