# Generated by Django 3.2 on 2023-07-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='edge',
            name='task',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='worker',
        ),
        migrations.DeleteModel(
            name='BipartiteGraph',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
    ]
