# Generated by Django 3.2 on 2023-07-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionhistory',
            name='graph_density',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bipartitegraph',
            name='edges',
            field=models.ManyToManyField(blank=True, to='management.Edge'),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='heuristic_matching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.heuristicmatching'),
        ),
        migrations.AlterField(
            model_name='executionhistory',
            name='max_matching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.maxmatching'),
        ),
        migrations.AlterField(
            model_name='heuristicmatching',
            name='heuristic_matching_edges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maxmatching',
            name='max_matching_edges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
