# Generated by Django 3.2 on 2023-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230724_1931'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='connected_tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
