# Generated by Django 3.2 on 2023-07-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_connected_workers'),
        ('workers', '0002_worker_connected_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='connected_tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
