# Generated by Django 3.2 on 2023-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_worker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], db_index=True, default='FREE', max_length=50),
        ),
    ]
