# Generated by Django 3.2 on 2023-11-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('PROGRESS', 'Progress')], db_index=True, default='OPEN', max_length=50),
        ),
    ]
