# Generated by Django 3.2 on 2023-07-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_connected_tasks'),
        ('tasks', '0002_auto_20230724_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='connected_workers',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='workers.Worker'),
        ),
    ]
